FROM python:3.7-alpine
RUN apk update
RUN apk add g++ 
RUN apk add pkgconfig
RUN apk add libpng-dev
RUN apk add freetype-dev
RUN apk add neovim
RUN apk add bash
RUN pip3 install numpy
RUN pip3 install matplotlib
RUN pip3 install pyjet
RUN pip3 install numpythia
COPY ./ /2dhists/
